In [2]:
import numpy as np

In [8]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)
print
cal = np.sum(A,axis=0)
print(cal)
print
per = 100 * A / cal.reshape(1,4)
print(per)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]

[  59.   239.   155.4   76.9]

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [11]:
a = np.array([[1],
              [2],
              [3]])
b = 100
print(a+b)

[[101]
 [102]
 [103]]


In [10]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([100,200,300])
print(a+b)

[[101 202 303]
 [104 205 306]]


In [12]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[100],[200]])
print(a+b)

[[101 102 103]
 [204 205 206]]
